[2025-06-13T14:14:38.213+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T14:13:33.890455+00:00 [queued]>
[2025-06-13T14:14:38.221+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T14:13:33.890455+00:00 [queued]>
[2025-06-13T14:14:38.221+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2025-06-13T14:14:38.260+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): generate_order_process> on 2025-06-13 14:13:33.890455+00:00
[2025-06-13T14:14:38.272+0000] {standard_task_runner.py:57} INFO - Started process 744 to run task
[2025-06-13T14:14:38.276+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_generate_order_process', 'generate_order_process', 'scheduled__2025-06-13T14:13:33.890455+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/generate_order_process.py', '--cfg-path', '/tmp/tmpn813df4z']
[2025-06-13T14:14:38.278+0000] {standard_task_runner.py:85} INFO - Job 46: Subtask generate_order_process
[2025-06-13T14:14:38.384+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T14:13:33.890455+00:00 [running]> on host 3bda607c6347
[2025-06-13T14:14:38.950+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_generate_order_process' AIRFLOW_CTX_TASK_ID='generate_order_process' AIRFLOW_CTX_EXECUTION_DATE='2025-06-13T14:13:33.890455+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-13T14:13:33.890455+00:00'
[2025-06-13T14:14:39.098+0000] {logging_mixin.py:151} INFO - ----------------------------
[2025-06-13T14:14:39.098+0000] {logging_mixin.py:151} INFO - 10
[2025-06-13T14:14:39.098+0000] {logging_mixin.py:151} INFO - ----------------------------
[2025-06-13T14:14:39.137+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/generate_order_process.py", line 21, in generate_order_process
    order_id = order.save_order()
  File "/usr/local/lib/python3.10/site-packages/ecommerce/models/order.py", line 112, in save_order
    discount_id = order_discount[0]
TypeError: 'NoneType' object is not subscriptable
[2025-06-13T14:14:39.311+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_generate_order_process, task_id=generate_order_process, execution_date=20250613T141333, start_date=20250613T141438, end_date=20250613T141439
[2025-06-13T14:14:39.470+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 46 for task generate_order_process ('NoneType' object is not subscriptable; 744)
[2025-06-13T14:14:39.570+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-13T14:14:40.763+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
