[2025-06-13T13:54:49.971+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T13:53:48.472387+00:00 [queued]>
[2025-06-13T13:54:49.981+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T13:53:48.472387+00:00 [queued]>
[2025-06-13T13:54:49.982+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2025-06-13T13:54:49.996+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): generate_order_process> on 2025-06-13 13:53:48.472387+00:00
[2025-06-13T13:54:50.001+0000] {standard_task_runner.py:57} INFO - Started process 286 to run task
[2025-06-13T13:54:50.003+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_generate_order_process', 'generate_order_process', 'scheduled__2025-06-13T13:53:48.472387+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/generate_order_process.py', '--cfg-path', '/tmp/tmp08ccliif']
[2025-06-13T13:54:50.005+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask generate_order_process
[2025-06-13T13:54:50.062+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T13:53:48.472387+00:00 [running]> on host f1d84043854e
[2025-06-13T13:54:50.158+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_generate_order_process' AIRFLOW_CTX_TASK_ID='generate_order_process' AIRFLOW_CTX_EXECUTION_DATE='2025-06-13T13:53:48.472387+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-13T13:53:48.472387+00:00'
[2025-06-13T13:54:50.171+0000] {logging_mixin.py:151} INFO - ----------------------------
[2025-06-13T13:54:50.171+0000] {logging_mixin.py:151} INFO - None
[2025-06-13T13:54:50.171+0000] {logging_mixin.py:151} INFO - ----------------------------
[2025-06-13T13:54:50.171+0000] {logging_mixin.py:151} INFO - None
[2025-06-13T13:54:50.186+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/generate_order_process.py", line 26, in generate_order_process
    raise AirflowException('Order not found...')
airflow.exceptions.AirflowException: Order not found...
[2025-06-13T13:54:50.188+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_generate_order_process, task_id=generate_order_process, execution_date=20250613T135348, start_date=20250613T135449, end_date=20250613T135450
[2025-06-13T13:54:50.201+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task generate_order_process (Order not found...; 286)
[2025-06-13T13:54:50.215+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-13T13:54:50.246+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
