[2025-06-13T15:51:26.557+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T15:50:24.365447+00:00 [queued]>
[2025-06-13T15:51:26.574+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T15:50:24.365447+00:00 [queued]>
[2025-06-13T15:51:26.575+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2025-06-13T15:51:26.604+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): generate_order_process> on 2025-06-13 15:50:24.365447+00:00
[2025-06-13T15:51:26.614+0000] {standard_task_runner.py:57} INFO - Started process 285 to run task
[2025-06-13T15:51:26.619+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_generate_order_process', 'generate_order_process', 'scheduled__2025-06-13T15:50:24.365447+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/generate_order_process.py', '--cfg-path', '/tmp/tmp4rksf2qz']
[2025-06-13T15:51:26.624+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask generate_order_process
[2025-06-13T15:51:26.766+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T15:50:24.365447+00:00 [running]> on host 3498b866135e
[2025-06-13T15:51:27.001+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_generate_order_process' AIRFLOW_CTX_TASK_ID='generate_order_process' AIRFLOW_CTX_EXECUTION_DATE='2025-06-13T15:50:24.365447+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-13T15:50:24.365447+00:00'
[2025-06-13T15:51:27.031+0000] {logging_mixin.py:151} INFO - ----------------------------
[2025-06-13T15:51:27.031+0000] {logging_mixin.py:151} INFO - None
[2025-06-13T15:51:27.032+0000] {logging_mixin.py:151} INFO - ----------------------------
[2025-06-13T15:51:27.032+0000] {logging_mixin.py:151} INFO - None
[2025-06-13T15:51:27.071+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/generate_order_process.py", line 26, in generate_order_process
    raise AirflowException('Order not found...')
airflow.exceptions.AirflowException: Order not found...
[2025-06-13T15:51:27.081+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_generate_order_process, task_id=generate_order_process, execution_date=20250613T155024, start_date=20250613T155126, end_date=20250613T155127
[2025-06-13T15:51:27.119+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task generate_order_process (Order not found...; 285)
[2025-06-13T15:51:27.152+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-13T15:51:27.212+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
