[2025-06-13T13:35:44.638+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T13:34:26.445784+00:00 [queued]>
[2025-06-13T13:35:44.662+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T13:34:26.445784+00:00 [queued]>
[2025-06-13T13:35:44.662+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2025-06-13T13:35:44.709+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): generate_order_process> on 2025-06-13 13:34:26.445784+00:00
[2025-06-13T13:35:44.731+0000] {standard_task_runner.py:57} INFO - Started process 226 to run task
[2025-06-13T13:35:44.747+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_generate_order_process', 'generate_order_process', 'scheduled__2025-06-13T13:34:26.445784+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/generate_order_process.py', '--cfg-path', '/tmp/tmpqzqqzaae']
[2025-06-13T13:35:44.761+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask generate_order_process
[2025-06-13T13:35:45.057+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T13:34:26.445784+00:00 [running]> on host 76a309d19f9c
[2025-06-13T13:35:45.412+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_generate_order_process' AIRFLOW_CTX_TASK_ID='generate_order_process' AIRFLOW_CTX_EXECUTION_DATE='2025-06-13T13:34:26.445784+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-13T13:34:26.445784+00:00'
[2025-06-13T13:35:45.476+0000] {logging_mixin.py:151} INFO - ----------------------------
[2025-06-13T13:35:45.477+0000] {logging_mixin.py:151} INFO - None
[2025-06-13T13:35:45.477+0000] {logging_mixin.py:151} INFO - ----------------------------
[2025-06-13T13:35:45.478+0000] {logging_mixin.py:151} INFO - None
[2025-06-13T13:35:45.533+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/generate_order_process.py", line 26, in generate_order_process
    raise AirflowException('Order not found...')
airflow.exceptions.AirflowException: Order not found...
[2025-06-13T13:35:45.546+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_generate_order_process, task_id=generate_order_process, execution_date=20250613T133426, start_date=20250613T133544, end_date=20250613T133545
[2025-06-13T13:35:45.587+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task generate_order_process (Order not found...; 226)
[2025-06-13T13:35:45.609+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-13T13:35:45.968+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
