[2025-06-13T14:05:44.605+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T14:04:27.213024+00:00 [queued]>
[2025-06-13T14:05:44.623+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T14:04:27.213024+00:00 [queued]>
[2025-06-13T14:05:44.623+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2025-06-13T14:05:44.663+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): generate_order_process> on 2025-06-13 14:04:27.213024+00:00
[2025-06-13T14:05:44.685+0000] {standard_task_runner.py:57} INFO - Started process 224 to run task
[2025-06-13T14:05:44.698+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_generate_order_process', 'generate_order_process', 'scheduled__2025-06-13T14:04:27.213024+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/generate_order_process.py', '--cfg-path', '/tmp/tmpelhs9rwt']
[2025-06-13T14:05:44.703+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask generate_order_process
[2025-06-13T14:05:44.953+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T14:04:27.213024+00:00 [running]> on host a30c1c73f42f
[2025-06-13T14:05:45.335+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_generate_order_process' AIRFLOW_CTX_TASK_ID='generate_order_process' AIRFLOW_CTX_EXECUTION_DATE='2025-06-13T14:04:27.213024+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-13T14:04:27.213024+00:00'
[2025-06-13T14:05:45.386+0000] {logging_mixin.py:151} INFO - ----------------------------
[2025-06-13T14:05:45.387+0000] {logging_mixin.py:151} INFO - None
[2025-06-13T14:05:45.387+0000] {logging_mixin.py:151} INFO - ----------------------------
[2025-06-13T14:05:45.388+0000] {logging_mixin.py:151} INFO - None
[2025-06-13T14:05:45.489+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/generate_order_process.py", line 26, in generate_order_process
    raise AirflowException('Order not found...')
airflow.exceptions.AirflowException: Order not found...
[2025-06-13T14:05:45.530+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_generate_order_process, task_id=generate_order_process, execution_date=20250613T140427, start_date=20250613T140544, end_date=20250613T140545
[2025-06-13T14:05:45.605+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task generate_order_process (Order not found...; 224)
[2025-06-13T14:05:45.669+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-13T14:05:45.777+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
