[2025-06-13T13:54:07.602+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T13:52:48.472387+00:00 [queued]>
[2025-06-13T13:54:07.649+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T13:52:48.472387+00:00 [queued]>
[2025-06-13T13:54:07.655+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2025-06-13T13:54:07.791+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): generate_order_process> on 2025-06-13 13:52:48.472387+00:00
[2025-06-13T13:54:07.823+0000] {standard_task_runner.py:57} INFO - Started process 225 to run task
[2025-06-13T13:54:07.839+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_generate_order_process', 'generate_order_process', 'scheduled__2025-06-13T13:52:48.472387+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/generate_order_process.py', '--cfg-path', '/tmp/tmp88ssjjjc']
[2025-06-13T13:54:07.846+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask generate_order_process
[2025-06-13T13:54:08.166+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_generate_order_process.generate_order_process scheduled__2025-06-13T13:52:48.472387+00:00 [running]> on host f1d84043854e
[2025-06-13T13:54:08.898+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ecommerce_generate_order_process' AIRFLOW_CTX_TASK_ID='generate_order_process' AIRFLOW_CTX_EXECUTION_DATE='2025-06-13T13:52:48.472387+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-13T13:52:48.472387+00:00'
[2025-06-13T13:54:09.021+0000] {logging_mixin.py:151} INFO - ----------------------------
[2025-06-13T13:54:09.022+0000] {logging_mixin.py:151} INFO - None
[2025-06-13T13:54:09.022+0000] {logging_mixin.py:151} INFO - ----------------------------
[2025-06-13T13:54:09.023+0000] {logging_mixin.py:151} INFO - None
[2025-06-13T13:54:09.118+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/generate_order_process.py", line 26, in generate_order_process
    raise AirflowException('Order not found...')
airflow.exceptions.AirflowException: Order not found...
[2025-06-13T13:54:09.134+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ecommerce_generate_order_process, task_id=generate_order_process, execution_date=20250613T135248, start_date=20250613T135407, end_date=20250613T135409
[2025-06-13T13:54:09.179+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2 for task generate_order_process (Order not found...; 225)
[2025-06-13T13:54:09.218+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-13T13:54:09.530+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
